version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing dependencies..."
      - npm install -g snyk --unsafe-perm
      - apt-get update
      - apt-get install -y wget
      - apt-get install -y openjdk-17-jdk
      - apt-get install -y python3-pip
      - pip3 install zapcli
  pre_build:
    commands:
      - echo "Authenticating Snyk..."
      - snyk auth $SNYK_TOKEN
      - echo "SONAR_TOKEN is set"
  build:
    commands:
      - echo "Running SonarQube analysis..."
      - mvn verify sonar:sonar -Dsonar.projectKey=devsecopsguru -Dsonar.organization=devsecopsguru -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=$SONAR_TOKEN
      - echo "Running Snyk security scan..."
      - snyk test
      - echo "Running OWASP ZAP..."
      - zap-cli start
      - sleep 60  # Allow extra time for ZAP to start
      - zap-cli status -vv  # Check ZAP status
      - zap-cli open-url https://example.com  # Replace with your actual URL
      - zap-cli spider https://example.com  # Replace with your actual URL
      - zap-cli active-scan https://example.com  # Replace with your actual URL
      - zap-cli report -o zap-report.html -f html
      - zap-cli stop
      - echo "ZAP scan completed. Listing current directory contents..."
      - ls -la  # Verify the ZAP report generation
  post_build:
    commands:
      - echo "Verifying ZAP report..."
      - ls -la  # List contents of the current directory to verify the report file
      - echo "Build, SonarQube analysis, Snyk security scan, and OWASP ZAP report completed."
artifacts:
  files:
    - zap-report.html
