version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing dependencies..."
      - npm install -g snyk --unsafe-perm
      - apt-get update
      - apt-get install -y wget
      - apt-get install -y docker.io  # Install Docker
  pre_build:
    commands:
      - echo "Authenticating Snyk..."
      - snyk auth $SNYK_TOKEN
      - echo "SONAR_TOKEN is set"
  build:
    commands:
      - echo "Running SonarQube analysis..."
      - mvn verify sonar:sonar -Dsonar.projectKey=devsecopsguru -Dsonar.organization=devsecopsguru -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=$SONAR_TOKEN
      - echo "Running Snyk security scan..."
      - snyk test
      - echo "Running OWASP ZAP using Docker..."
      - mkdir -p zap  # Ensure the 'zap' directory exists
      - docker run --rm -v $(pwd)/zap:/zap/wrk -t owasp/zap2docker-stable zap-baseline.py -t https://example.com -r zap-report.html  # Replace with your actual URL
      - echo "ZAP scan completed. Listing zap directory contents..."
      - ls -la zap  # Verify the ZAP report generation
  post_build:
    commands:
      - echo "Verifying ZAP report..."
      - ls -la zap  # List contents of the 'zap' directory to verify the report file
      - echo "Build, SonarQube analysis, Snyk security scan, and OWASP ZAP report completed."
artifacts:
  files:
    - zap/zap-report.html
