version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing dependencies..."
      - npm install -g snyk --unsafe-perm
      - apt-get update
      - apt-get install -y wget
      - wget https://github.com/zaproxy/zaproxy/releases/download/v2.16.0/ZAP_2.16.0_Core.zip
      - mkdir zap
      - unzip ZAP_2.16.0_Core.zip -d zap
  pre_build:
    commands:
      - echo "Authenticating Snyk..."
      - snyk auth $SNYK_TOKEN
      - echo "SONAR_TOKEN is set"
  build:
    commands:
      - echo "Running SonarQube analysis..."
      - mvn verify sonar:sonar -Dsonar.projectKey=devsecopsguru -Dsonar.organization=devsecopsguru -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=$SONAR_TOKEN
      - echo "Running Snyk security scan..."
      - snyk test
      - echo "Running OWASP ZAP..."
      - zap/zap.sh -daemon -port 8080 &
      - sleep 30  # Allow some time for ZAP to start
      - zap/zap.sh -cmd -quickurl https://example.com -quickout zap/zap-report.html  # Ensure report is generated in 'zap' directory
  post_build:
    commands:
      - echo "Verifying ZAP report..."
      - ls -la zap  # List contents of the 'zap' directory to verify the report file
      - echo "Build, SonarQube analysis, Snyk security scan, and OWASP ZAP report completed."
artifacts:
  files:
    - zap/zap-report.html
